  fun ref take_error(error': GError): None =>
    GSimpleAsyncResultP.take_error(this, error')
